In [85]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

X, y, iris.target_names, iris.feature_names

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train, X_test, y_train, y_test

(array([[4.9, 3.1, 1.5, 0.1],
        [5.4, 3.9, 1.7, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.9, 3. , 5.1, 1.8],
        [5.1, 3.3, 1.7, 0.5],
        [6.1, 2.8, 4. , 1.3],
        [4.7, 3.2, 1.3, 0.2],
        [5.8, 2.7, 5.1, 1.9],
        [6.9, 3.2, 5.7, 2.3],
        [6.4, 2.8, 5.6, 2.1],
        [5. , 3.5, 1.3, 0.3],
        [7.2, 3.2, 6. , 1.8],
        [4.4, 3.2, 1.3, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.6, 2.9, 3.6, 1.3],
        [5.2, 4.1, 1.5, 0.1],
        [5.7, 3.8, 1.7, 0.3],
        [4.9, 3. , 1.4, 0.2],
        [7.4, 2.8, 6.1, 1.9],
        [6.1, 2.6, 5.6, 1.4],
        [6.3, 3.4, 5.6, 2.4],
        [5.6, 2.5, 3.9, 1.1],
        [5. , 2. , 3.5, 1. ],
        [5.1, 3.8, 1.6, 0.2],
        [7.1, 3. , 5.9, 2.1],
        [6.4, 2.7, 5.3, 1.9],
        [6.7, 3. , 5. , 1.7],
        [5.7, 4.4, 1.5, 0.4],
        [5.8, 2.7, 4.1, 1. ],
        [6.4, 3.2, 4.5, 1.5],
        [6.6, 2.9, 4.6, 1.3],
        [6.7, 3.1, 5.6, 2.4],
        [5.7, 3. , 4.2, 1.2],
        [5

In [87]:
X.shape, X_train.shape, X_test.shape, X_train.shape[0] / X.shape[0], X_test.shape[0] / X.shape[0]

((150, 4), (112, 4), (38, 4), 0.7466666666666667, 0.25333333333333335)

In [88]:
y.shape, y_train.shape, y_test.shape, y_train.shape[0] / y.shape[0], y_test.shape[0] / y.shape[0]

((150,), (112,), (38,), 0.7466666666666667, 0.25333333333333335)

In [89]:
y.reshape((150, 1)),y.reshape((-1,))

(array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [90]:
from sklearn.neighbors import KNeighborsClassifier

estimator = KNeighborsClassifier(n_neighbors=3)

estimator.fit(X_train, y_train)

y_predicted = estimator.predict(X_test)

print("Precisión: {:.1f}".format((y_test == y_predicted).mean() * 100))

Precisión: 100.0


In [91]:
X_test, y_test, y_predicted

(array([[4.6, 3.2, 1.4, 0.2],
        [5.5, 2.4, 3.8, 1.1],
        [6.3, 2.5, 5. , 1.9],
        [5. , 3.4, 1.6, 0.4],
        [5. , 3.3, 1.4, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [5.6, 2.8, 4.9, 2. ],
        [4.9, 3.6, 1.4, 0.1],
        [5.7, 2.8, 4.1, 1.3],
        [4.7, 3.2, 1.6, 0.2],
        [6.3, 2.9, 5.6, 1.8],
        [6.7, 3.1, 4.7, 1.5],
        [6.2, 2.2, 4.5, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [5.6, 2.7, 4.2, 1.3],
        [5.9, 3. , 4.2, 1.5],
        [6.9, 3.1, 5.1, 2.3],
        [5.4, 3.4, 1.5, 0.4],
        [5.7, 2.5, 5. , 2. ],
        [6.8, 3. , 5.5, 2.1],
        [6.3, 2.7, 4.9, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.3, 3.3, 6. , 2.5],
        [6.3, 3.3, 4.7, 1.6],
        [5.8, 2.7, 3.9, 1.2],
        [4.6, 3.6, 1. , 0.2],
        [7.2, 3. , 5.8, 1.6],
        [6.7, 3.1, 4.4, 1.4],
        [5.4, 3.4, 1.7, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [7.3, 2.9, 6.3, 1.8],
        [6.1, 2.8, 4.7, 1.2],
        [7

In [92]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(estimator, X, y, scoring='accuracy')

print(scores)

[0.96666667 0.96666667 0.93333333 0.96666667 1.        ]


In [93]:
accuracy = scores.mean() * 100

accuracy

96.66666666666669

In [94]:
import numpy as np

x = np.random.uniform(5, 20, (10, 4))

x

array([[13.56692106, 12.81854332, 15.38314793, 14.90489084],
       [10.20658018,  8.96365329, 14.04901228,  6.51911889],
       [ 8.91462437, 19.21417042, 17.05260681, 12.44858791],
       [ 5.62784733, 15.6046075 , 11.90736176, 18.27108173],
       [ 9.87581775, 16.47720905, 18.23656034,  5.94861116],
       [ 6.43805921, 16.62772889, 17.02262823, 16.5805082 ],
       [16.17921171,  6.41752099, 19.48775376,  7.60267337],
       [ 7.95166467,  5.44025846,  5.66156155, 16.51348475],
       [10.44927032,  9.52463066,  7.31838685,  7.44220895],
       [11.49493304, 19.12853929,  7.67299259, 13.98138071]])

In [95]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler().fit_transform(x)

array([[0.75242153, 0.53567098, 0.70312825, 0.726825  ],
       [0.43394699, 0.25580204, 0.6066349 , 0.04629816],
       [0.31150256, 1.        , 0.82387436, 0.52748974],
       [0.        , 0.73794207, 0.45173683, 1.        ],
       [0.40259916, 0.80129382, 0.90950557, 0.        ],
       [0.0767874 , 0.81222172, 0.82170612, 0.86280563],
       [1.        , 0.07095025, 1.        , 0.13423138],
       [0.22023856, 0.        , 0.        , 0.85736651],
       [0.45694782, 0.29652957, 0.11983236, 0.12120928],
       [0.55604996, 0.99378309, 0.14547975, 0.65187979]])

In [96]:
from sklearn.preprocessing import Normalizer

Normalizer().fit_transform(x)

array([[0.47752694, 0.45118562, 0.54145428, 0.52462064],
       [0.49544462, 0.43511085, 0.68196275, 0.31644903],
       [0.29808069, 0.64246939, 0.5701926 , 0.41624678],
       [0.20539122, 0.56949828, 0.43456537, 0.66681264],
       [0.36378331, 0.60695061, 0.67175767, 0.21912165],
       [0.21670542, 0.55969026, 0.5729826 , 0.55810081],
       [0.59454892, 0.23582918, 0.71613025, 0.27938081],
       [0.3987945 , 0.27284163, 0.28394049, 0.82818971],
       [0.59458149, 0.5419679 , 0.41642883, 0.42347452],
       [0.41906889, 0.69736602, 0.27973303, 0.50971691]])

In [97]:
from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(x)

array([[ 1.16207539, -0.04172028,  0.42420352,  0.64478559],
       [ 0.04523005, -0.83341482,  0.14178831, -1.23028621],
       [-0.38416533,  1.27177582,  0.7776013 ,  0.09555239],
       [-1.47656093,  0.53046512, -0.31156491,  1.39747117],
       [-0.0647024 ,  0.70967486,  1.02822536, -1.35785264],
       [-1.20727833,  0.74058774,  0.77125532,  1.01945627],
       [ 2.03029821, -1.35632442,  1.29308302, -0.98800173],
       [-0.70421531, -1.55702882, -1.63370107,  1.00446972],
       [ 0.12589072, -0.7182046 , -1.28297761, -1.02388183],
       [ 0.47342794,  1.2541894 , -1.20791324,  0.43828727]])

In [98]:
from sklearn.preprocessing import Binarizer

Binarizer().fit_transform(MinMaxScaler().fit_transform(x))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
X_broken = np.array(X)

X_broken[:,::3] /= 4

X_broken

array([[1.275, 3.5  , 1.4  , 0.05 ],
       [1.225, 3.   , 1.4  , 0.05 ],
       [1.175, 3.2  , 1.3  , 0.05 ],
       [1.15 , 3.1  , 1.5  , 0.05 ],
       [1.25 , 3.6  , 1.4  , 0.05 ],
       [1.35 , 3.9  , 1.7  , 0.1  ],
       [1.15 , 3.4  , 1.4  , 0.075],
       [1.25 , 3.4  , 1.5  , 0.05 ],
       [1.1  , 2.9  , 1.4  , 0.05 ],
       [1.225, 3.1  , 1.5  , 0.025],
       [1.35 , 3.7  , 1.5  , 0.05 ],
       [1.2  , 3.4  , 1.6  , 0.05 ],
       [1.2  , 3.   , 1.4  , 0.025],
       [1.075, 3.   , 1.1  , 0.025],
       [1.45 , 4.   , 1.2  , 0.05 ],
       [1.425, 4.4  , 1.5  , 0.1  ],
       [1.35 , 3.9  , 1.3  , 0.1  ],
       [1.275, 3.5  , 1.4  , 0.075],
       [1.425, 3.8  , 1.7  , 0.075],
       [1.275, 3.8  , 1.5  , 0.075],
       [1.35 , 3.4  , 1.7  , 0.05 ],
       [1.275, 3.7  , 1.5  , 0.1  ],
       [1.15 , 3.6  , 1.   , 0.05 ],
       [1.275, 3.3  , 1.7  , 0.125],
       [1.2  , 3.4  , 1.9  , 0.05 ],
       [1.25 , 3.   , 1.6  , 0.05 ],
       [1.25 , 3.4  , 1.6  , 0.1  ],
 

In [100]:
estimator = KNeighborsClassifier()

scores = cross_val_score(estimator, X_broken, y, scoring='accuracy')

scores.mean()

0.9466666666666667

In [101]:
from sklearn.pipeline import Pipeline

sequence = Pipeline([
    ('scale', MinMaxScaler()),
    ('estimate', KNeighborsClassifier())
])

scores = cross_val_score(sequence, X_broken, y, scoring='accuracy')

scores.mean()

0.96

In [102]:
import pandas as pd

games = pd.read_csv("../data/basketball/NBA_2016_games.csv", parse_dates=["Date"])

games.columns = ["DATE", "START", "VISITOR_TEAM", "VISITOR_POINTS", "HOME_TEAM", "HOME_POINTS", "BOX", "OT", "ATTEND", "ARENA", "NOTES"]

games

DATE   START           VISITOR_TEAM  VISITOR_POINTS   
0    2015-10-27   8:00p    Cleveland Cavaliers              95  \
1    2015-10-27   8:00p        Detroit Pistons             106   
2    2015-10-27  10:30p   New Orleans Pelicans              95   
3    2015-10-28   7:00p     Washington Wizards              88   
4    2015-10-28   7:30p     Philadelphia 76ers              95   
...         ...     ...                    ...             ...   
1311 2016-06-08   9:00p  Golden State Warriors              90   
1312 2016-06-10   9:00p  Golden State Warriors             108   
1313 2016-06-13   9:00p    Cleveland Cavaliers             112   
1314 2016-06-16   9:00p  Golden State Warriors             101   
1315 2016-06-19   8:00p    Cleveland Cavaliers              93   

                  HOME_TEAM  HOME_POINTS        BOX   OT  ATTEND   
0             Chicago Bulls           97  Box Score  NaN   21957  \
1             Atlanta Hawks           94  Box Score  NaN   19187   
2     Golden State Warriors          111  Box Score  NaN   19596   
3             Orlando Magic           87  Box Score  NaN   18846   
4            Boston Celtics          112  Box Score  NaN   18624   
...                     ...          ...        ...  ...     ...   
1311    Cleveland Cavaliers          120  Box Score  NaN   20562   
1312    Cleveland Cavaliers           97  Box Score  NaN   20562   
1313  Golden State Warriors           97  Box Score  NaN   19596   
1314    Cleveland Cavaliers          115  Box Score  NaN   20562   
1315  Golden State Warriors           89  Box Score  NaN   19596   

                    ARENA NOTES  
0           United Center   NaN  
1           Philips Arena   NaN  
2            Oracle Arena   NaN  
3            Amway Center   NaN  
4               TD Garden   NaN  
...                   ...   ...  
1311  Quicken Loans Arena   NaN  
1312  Quicken Loans Arena   NaN  
1313         Oracle Arena   NaN  
1314  Quicken Loans Arena   NaN  
1315         Oracle Arena   NaN  

[1316 rows x 11 columns]

In [103]:
games["HOME_WIN"] = games["VISITOR_POINTS"] < games["HOME_POINTS"]

games.sample(5)

DATE  START           VISITOR_TEAM  VISITOR_POINTS   
1027 2016-03-19  6:00p         Denver Nuggets             101  \
1214 2016-04-12  8:00p  Oklahoma City Thunder              98   
180  2015-11-20  8:00p        Detroit Pistons              96   
521  2016-01-05  8:00p        Milwaukee Bucks             106   
1067 2016-03-24  7:00p   New Orleans Pelicans              84   

                   HOME_TEAM  HOME_POINTS        BOX   OT  ATTEND   
1027       Charlotte Hornets           93  Box Score  NaN   19271  \
1214       San Antonio Spurs          102  Box Score   OT   18765   
180   Minnesota Timberwolves           86  Box Score  NaN   13445   
521            Chicago Bulls          117  Box Score  NaN   21686   
1067          Indiana Pacers           92  Box Score  NaN   17517   

                        ARENA NOTES  HOME_WIN  
1027  Time Warner Cable Arena   NaN     False  
1214              AT&T Center   NaN      True  
180             Target Center   NaN     False  
521             United Center   NaN      True  
1067  Bankers Life Fieldhouse   NaN      True

In [104]:
games["HOME_WIN"].mean()

0.5942249240121581

In [105]:
from collections import defaultdict

won_last = defaultdict(int)

for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    games.at[index, "HOME_LAST_WIN"] = bool(won_last[home_team])
    games.at[index, "VISITOR_LAST_WIN"] = bool(won_last[visitor_team])

    if row["HOME_WIN"]:
        # print("WIN HOME: {} vs {}".format(home_team, visitor_team))
        won_last[home_team] = 1
        won_last[visitor_team] = 0
    else:
        # print("WIN VISITOR: {} vs {}".format(home_team, visitor_team))
        won_last[home_team] = 0
        won_last[visitor_team] = 1

games

DATE   START           VISITOR_TEAM  VISITOR_POINTS   
0    2015-10-27   8:00p    Cleveland Cavaliers              95  \
1    2015-10-27   8:00p        Detroit Pistons             106   
2    2015-10-27  10:30p   New Orleans Pelicans              95   
3    2015-10-28   7:00p     Washington Wizards              88   
4    2015-10-28   7:30p     Philadelphia 76ers              95   
...         ...     ...                    ...             ...   
1311 2016-06-08   9:00p  Golden State Warriors              90   
1312 2016-06-10   9:00p  Golden State Warriors             108   
1313 2016-06-13   9:00p    Cleveland Cavaliers             112   
1314 2016-06-16   9:00p  Golden State Warriors             101   
1315 2016-06-19   8:00p    Cleveland Cavaliers              93   

                  HOME_TEAM  HOME_POINTS        BOX   OT  ATTEND   
0             Chicago Bulls           97  Box Score  NaN   21957  \
1             Atlanta Hawks           94  Box Score  NaN   19187   
2     Golden State Warriors          111  Box Score  NaN   19596   
3             Orlando Magic           87  Box Score  NaN   18846   
4            Boston Celtics          112  Box Score  NaN   18624   
...                     ...          ...        ...  ...     ...   
1311    Cleveland Cavaliers          120  Box Score  NaN   20562   
1312    Cleveland Cavaliers           97  Box Score  NaN   20562   
1313  Golden State Warriors           97  Box Score  NaN   19596   
1314    Cleveland Cavaliers          115  Box Score  NaN   20562   
1315  Golden State Warriors           89  Box Score  NaN   19596   

                    ARENA NOTES  HOME_WIN HOME_LAST_WIN VISITOR_LAST_WIN  
0           United Center   NaN      True         False            False  
1           Philips Arena   NaN     False         False            False  
2            Oracle Arena   NaN      True         False            False  
3            Amway Center   NaN     False         False            False  
4               TD Garden   NaN      True         False            False  
...                   ...   ...       ...           ...              ...  
1311  Quicken Loans Arena   NaN      True         False             True  
1312  Quicken Loans Arena   NaN     False          True            False  
1313         Oracle Arena   NaN     False          True            False  
1314  Quicken Loans Arena   NaN      True          True            False  
1315         Oracle Arena   NaN     False         False             True  

[1316 rows x 14 columns]

In [106]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [1, 0],
        [1, 0],
        [0, 1]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [107]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

59.42245650420554

In [108]:
standings = pd.read_csv("../data/basketball/NBA_2015_standings.csv")

standings

Rk                    Team Overall   Home   Road      E      W     A   
0    1   Golden State Warriors   67-15   39-2  28-13   25-5  42-10   9-1  \
1    2           Atlanta Hawks   60-22   35-6  25-16  38-14   22-8  12-6   
2    3         Houston Rockets   56-26  30-11  26-15   23-7  33-19   9-1   
3    4    Los Angeles Clippers   56-26  30-11  26-15  19-11  37-15   7-3   
4    5       Memphis Grizzlies   55-27  31-10  24-17  20-10  35-17   8-2   
5    6       San Antonio Spurs   55-27   33-8  22-19   23-7  32-20   7-3   
6    7     Cleveland Cavaliers   53-29  31-10  22-19  35-17  18-12  12-6   
7    8  Portland Trail Blazers   51-31   32-9  19-22  20-10  31-21   8-2   
8    9           Chicago Bulls   50-32  27-14  23-18  33-19  17-13  16-2   
9   10        Dallas Mavericks   50-32  27-14  23-18   21-9  29-23   9-1   
10  11         Toronto Raptors   49-33  27-14  22-19  33-19  16-14  11-5   
11  12      Washington Wizards   46-36  29-12  17-24  30-22  16-14  11-7   
12  13    New Orleans Pelicans   45-37  28-13  17-24  16-14  29-23   6-4   
13  14   Oklahoma City Thunder   45-37  29-12  16-25  20-10  25-27   6-4   
14  15         Milwaukee Bucks   41-41  23-18  18-23  30-22  11-19  14-4   
15  16          Boston Celtics   40-42  21-20  19-22  28-24  12-18  12-4   
16  17            Phoenix Suns   39-43  22-19  17-24  18-12  21-31   8-2   
17  18           Brooklyn Nets   38-44  19-22  19-22  24-28  14-16  10-6   
18  19          Indiana Pacers   38-44  23-18  15-26  28-24  10-20   9-9   
19  20               Utah Jazz   38-44  21-20  17-24  15-15  23-29   6-4   
20  21              Miami Heat   37-45  20-21  17-24  25-27  12-18  14-4   
21  22       Charlotte Hornets   33-49  19-22  14-27  25-27   8-22  10-8   
22  23         Detroit Pistons   32-50  18-23  14-27  23-29   9-21  8-10   
23  24          Denver Nuggets   30-52  19-22  11-30  11-19  19-33   1-9   
24  25        Sacramento Kings   29-53  18-23  11-30  11-19  18-34   4-6   
25  26           Orlando Magic   25-57  13-28  12-29  15-37  10-20  6-12   
26  27      Los Angeles Lakers   21-61  12-29   9-32  12-18   9-43   4-6   
27  28      Philadelphia 76ers   18-64  12-29   6-35  12-40   6-24  2-14   
28  29         New York Knicks   17-65  10-31   7-34  11-41   6-24  5-11   
29  30  Minnesota Timberwolves   16-66   9-32   7-34   9-21   7-45   4-6   

       C    SE  ...   Post    ≤3    ≥10  Oct   Nov   Dec   Jan  Feb   Mar  Apr  
0    7-3   9-1  ...   25-6   5-3   45-9  1-0  13-2  11-3  12-3  8-3  16-2  6-2  
1   14-4  12-4  ...  17-11   6-4  30-10  0-1   9-5  14-2  17-0  7-4   9-7  4-3  
2    8-2   6-4  ...   20-9   8-4  31-14  2-0  11-4   9-5  11-6  7-3  10-6  6-2  
3    6-4   6-4  ...   21-7   3-5   33-9  2-0   9-5  11-6  11-4  5-6  11-5  7-0  
4    5-5   7-3  ...  16-13   9-3  26-13  2-0  13-2   8-6  12-4  7-4   9-8  4-3  
5    7-3   9-1  ...   21-8   6-7   34-7  1-1  11-3  8-10  10-4  6-5  12-3  7-1  
6   11-5  12-6  ...   20-7   6-4  30-14  1-1   7-6  10-7  11-6  8-3  11-4  5-2  
7    7-3   5-5  ...  15-14   5-1  30-11  1-1  12-3  13-3   6-9  6-3  10-6  3-6  
8    8-8   9-9  ...  16-12   7-2  20-16  1-1  10-5  11-4   8-9  7-3   8-7  5-3  
9    5-5   7-3  ...  14-13   5-4  22-18  1-1  12-4  10-5   9-7  7-5   6-7  5-3  
10  8-10  14-4  ...  13-16   6-5  29-11  1-0  12-4  11-4   9-7  4-7   7-8  5-3  
11   9-9  10-6  ...  13-15   9-4  21-14  1-1   9-4  12-4   9-8  3-9   7-7  5-3  
12   5-5   5-5  ...  18-11  10-4  19-14  1-0   6-8   9-8   9-6  6-5   8-7  6-3  
13   5-5   9-1  ...  17-12   4-8  26-14  0-2  5-10  11-5   7-7  9-3  10-5  3-5  
14   7-9   9-9  ...  11-18   5-9  17-16  1-1   9-7   7-8   8-6  7-5  4-11  5-3  
15   9-9  7-11  ...  20-11   8-6  17-14  1-0  3-10   7-8  5-11  7-4  10-8  7-1  
16   6-4   4-6  ...  10-18  4-12  14-19  2-0   8-8   8-8  10-5  3-8   7-8  1-6  
17  7-11  7-11  ...  17-13  10-2  15-23  0-1   6-8   9-7  3-12  6-5   9-7  5-4  
18   8-8  11-7  ...  17-11  4-12  19-20  1-1   6-9  5-11  5-11  7-2   8-8  6-2  
19   6-4   3-7  ...  19-10 

In [109]:
for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    home_rank = standings[ (standings["Team"] == home_team) ]["Rk"].values[0]
    visitor_rank = standings[ (standings["Team"] == visitor_team) ]["Rk"].values[0]

    games.at[index, "HOME_RANK"] = home_rank
    games.at[index, "VISITOR_RANK"] = visitor_rank
    games.at[index, "HOME_RANK_HIGHER"] = home_rank < visitor_rank

games

DATE   START           VISITOR_TEAM  VISITOR_POINTS   
0    2015-10-27   8:00p    Cleveland Cavaliers              95  \
1    2015-10-27   8:00p        Detroit Pistons             106   
2    2015-10-27  10:30p   New Orleans Pelicans              95   
3    2015-10-28   7:00p     Washington Wizards              88   
4    2015-10-28   7:30p     Philadelphia 76ers              95   
...         ...     ...                    ...             ...   
1311 2016-06-08   9:00p  Golden State Warriors              90   
1312 2016-06-10   9:00p  Golden State Warriors             108   
1313 2016-06-13   9:00p    Cleveland Cavaliers             112   
1314 2016-06-16   9:00p  Golden State Warriors             101   
1315 2016-06-19   8:00p    Cleveland Cavaliers              93   

                  HOME_TEAM  HOME_POINTS        BOX   OT  ATTEND   
0             Chicago Bulls           97  Box Score  NaN   21957  \
1             Atlanta Hawks           94  Box Score  NaN   19187   
2     Golden State Warriors          111  Box Score  NaN   19596   
3             Orlando Magic           87  Box Score  NaN   18846   
4            Boston Celtics          112  Box Score  NaN   18624   
...                     ...          ...        ...  ...     ...   
1311    Cleveland Cavaliers          120  Box Score  NaN   20562   
1312    Cleveland Cavaliers           97  Box Score  NaN   20562   
1313  Golden State Warriors           97  Box Score  NaN   19596   
1314    Cleveland Cavaliers          115  Box Score  NaN   20562   
1315  Golden State Warriors           89  Box Score  NaN   19596   

                    ARENA NOTES  HOME_WIN HOME_LAST_WIN VISITOR_LAST_WIN   
0           United Center   NaN      True         False            False  \
1           Philips Arena   NaN     False         False            False   
2            Oracle Arena   NaN      True         False            False   
3            Amway Center   NaN     False         False            False   
4               TD Garden   NaN      True         False            False   
...                   ...   ...       ...           ...              ...   
1311  Quicken Loans Arena   NaN      True         False             True   
1312  Quicken Loans Arena   NaN     False          True            False   
1313         Oracle Arena   NaN     False          True            False   
1314  Quicken Loans Arena   NaN      True          True            False   
1315         Oracle Arena   NaN     False         False             True   

      HOME_RANK  VISITOR_RANK HOME_RANK_HIGHER  
0           9.0           7.0            False  
1           2.0          23.0             True  
2           1.0          13.0             True  
3          26.0          12.0            False  
4          16.0          28.0             True  
...         ...           ...              ...  
1311        7.0           1.0            False  
1312        7.0           1.0            False  
1313        1.0           7.0             True  
1314        7.0           1.0            False  
1315        1.0           7.0             True  

[1316 rows x 17 columns]

In [110]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN", "HOME_RANK_HIGHER"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        ...,
        [1, 0, 1],
        [1, 0, 0],
        [0, 1, 1]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [111]:
scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

61.77670238506741

In [112]:
last_winner_match_teams =defaultdict(str)

for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    match_team = tuple(sorted([home_team, visitor_team]))

    home_win_last_match = False

    if last_winner_match_teams[match_team] == home_team:
        home_win_last_match = True

    games.at[index, "HOME_WIN_LAST_MATCH"] = home_win_last_match

    winner = visitor_team

    if row["HOME_WIN"]:
        winner = home_team

    last_winner_match_teams[match_team] = winner

games

DATE   START           VISITOR_TEAM  VISITOR_POINTS   
0    2015-10-27   8:00p    Cleveland Cavaliers              95  \
1    2015-10-27   8:00p        Detroit Pistons             106   
2    2015-10-27  10:30p   New Orleans Pelicans              95   
3    2015-10-28   7:00p     Washington Wizards              88   
4    2015-10-28   7:30p     Philadelphia 76ers              95   
...         ...     ...                    ...             ...   
1311 2016-06-08   9:00p  Golden State Warriors              90   
1312 2016-06-10   9:00p  Golden State Warriors             108   
1313 2016-06-13   9:00p    Cleveland Cavaliers             112   
1314 2016-06-16   9:00p  Golden State Warriors             101   
1315 2016-06-19   8:00p    Cleveland Cavaliers              93   

                  HOME_TEAM  HOME_POINTS        BOX   OT  ATTEND   
0             Chicago Bulls           97  Box Score  NaN   21957  \
1             Atlanta Hawks           94  Box Score  NaN   19187   
2     Golden State Warriors          111  Box Score  NaN   19596   
3             Orlando Magic           87  Box Score  NaN   18846   
4            Boston Celtics          112  Box Score  NaN   18624   
...                     ...          ...        ...  ...     ...   
1311    Cleveland Cavaliers          120  Box Score  NaN   20562   
1312    Cleveland Cavaliers           97  Box Score  NaN   20562   
1313  Golden State Warriors           97  Box Score  NaN   19596   
1314    Cleveland Cavaliers          115  Box Score  NaN   20562   
1315  Golden State Warriors           89  Box Score  NaN   19596   

                    ARENA NOTES  HOME_WIN HOME_LAST_WIN VISITOR_LAST_WIN   
0           United Center   NaN      True         False            False  \
1           Philips Arena   NaN     False         False            False   
2            Oracle Arena   NaN      True         False            False   
3            Amway Center   NaN     False         False            False   
4               TD Garden   NaN      True         False            False   
...                   ...   ...       ...           ...              ...   
1311  Quicken Loans Arena   NaN      True         False             True   
1312  Quicken Loans Arena   NaN     False          True            False   
1313         Oracle Arena   NaN     False          True            False   
1314  Quicken Loans Arena   NaN      True          True            False   
1315         Oracle Arena   NaN     False         False             True   

      HOME_RANK  VISITOR_RANK HOME_RANK_HIGHER HOME_WIN_LAST_MATCH  
0           9.0           7.0            False               False  
1           2.0          23.0             True               False  
2           1.0          13.0             True               False  
3          26.0          12.0            False               False  
4          16.0          28.0             True               False  
...         ...           ...              ...                 ...  
1311        7.0           1.0            False               False  
1312        7.0           1.0            False                True  
1313        1.0           7.0             True                True  
1314        7.0           1.0            False                True  
1315        1.0           7.0             True               False  

[1316 rows x 18 columns]

In [113]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN", "HOME_RANK_HIGHER", "HOME_WIN_LAST_MATCH"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        ...,
        [1, 0, 1, 1],
        [1, 0, 0, 1],
        [0, 1, 1, 0]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [114]:
scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

62.386219610554214

In [115]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

62.46226523793064

In [117]:
from sklearn.model_selection import GridSearchCV

parameter_space = {
    "max_features": [2, 10],
    "n_estimators": [100, 200],
    "criterion": ["gini", "entropy"],
    "min_samples_leaf": [2, 4, 6]
}

estimator = RandomForestClassifier(random_state=14)

grid = GridSearchCV(estimator, parameter_space)

scores = cross_val_score(grid, X, y, scoring='accuracy')

100 * scores.mean()

62.46226523793064

In [1]:
import pandas as pd

ratings = pd.read_csv("../data/ml-latest-small/ratings.csv")

ratings.sample(5)

userId  movieId  rating   timestamp
91412     593      593     4.0  1181007635
35966     245     3252     3.0   951183441
62242     413      527     5.0  1484439759
91046     590     5266     2.5  1267150640
84912     551   112852     3.0  1504320843

In [2]:
ratings["favorable"] = ratings["rating"] > 3

ratings.sample(5)

userId  movieId  rating   timestamp  favorable
67007     432    57274     5.0  1316391360       True
57717     380    45666     2.0  1494696322      False
96095     602      761     3.0   840876597      False
82105     520     4306     4.0  1326609180       True
76773     480     5943     1.5  1179166136      False

In [7]:
ratings_200 = ratings[ (ratings["userId"].isin(range(200))) ]

ratings_200.sample(5)

userId  movieId  rating   timestamp  favorable
26839     182     4896     4.0  1054782973       True
11787      72     1196     4.5  1217324882       True
13895      89   103602     5.0  1520408944       True
22266     149     1676     5.0   902084966       True
12979      83     1225     5.0  1332840366       True

In [15]:
favorable_ratings = ratings_200[ (ratings_200["favorable"]) ].groupby("userId")["movieId"]

favorable_reviews_by_user = dict((userId, movies.values) for userId, movies in favorable_ratings)

favorable_reviews_by_user

{1: array([   1,    3,    6,   47,   50,  101,  110,  151,  157,  163,  216,
         231,  235,  260,  333,  349,  356,  362,  367,  441,  457,  480,
         527,  543,  552,  553,  590,  592,  593,  596,  608,  661,  733,
         804,  919,  923,  940,  943,  954, 1023, 1024, 1025, 1029, 1031,
        1032, 1042, 1049, 1060, 1073, 1080, 1089, 1090, 1092, 1097, 1127,
        1136, 1196, 1197, 1198, 1206, 1208, 1210, 1213, 1214, 1220, 1222,
        1224, 1226, 1240, 1256, 1265, 1270, 1275, 1278, 1282, 1291, 1298,
        1348, 1473, 1500, 1517, 1552, 1573, 1587, 1617, 1620, 1625, 1732,
        1777, 1793, 1804, 1805, 1920, 1927, 1954, 1967, 2000, 2005, 2012,
        2018, 2028, 2033, 2046, 2048, 2054, 2058, 2078, 2090, 2094, 2096,
        2099, 2105, 2115, 2116, 2137, 2139, 2141, 2143, 2161, 2174, 2193,
        2268, 2273, 2291, 2329, 2353, 2366, 2387, 2395, 2406, 2427, 2450,
        2459, 2470, 2478, 2492, 2502, 2529, 2542, 2571, 2580, 2596, 2616,
        2628, 2640, 2641, 2644, 264

In [12]:
favorable_movies = ratings_200[ ["movieId", "favorable"] ].groupby("movieId").sum()

favorable_movies = favorable_movies.sort_values(by="favorable", ascending=False)

favorable_movies.head()

favorable
movieId           
318             95
356             88
296             79
593             77
260             71