In [20]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

X, y, iris.target_names, iris.feature_names

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train, X_test, y_train, y_test

(array([[6. , 3.4, 4.5, 1.6],
        [5. , 2. , 3.5, 1. ],
        [5. , 2.3, 3.3, 1. ],
        [7.2, 3. , 5.8, 1.6],
        [5.6, 2.8, 4.9, 2. ],
        [5.4, 3.7, 1.5, 0.2],
        [5.4, 3.9, 1.3, 0.4],
        [6.4, 3.2, 4.5, 1.5],
        [5.4, 3.9, 1.7, 0.4],
        [6.6, 3. , 4.4, 1.4],
        [5.2, 3.5, 1.5, 0.2],
        [6.8, 2.8, 4.8, 1.4],
        [6. , 2.9, 4.5, 1.5],
        [5.6, 2.7, 4.2, 1.3],
        [6.1, 3. , 4.9, 1.8],
        [6.8, 3. , 5.5, 2.1],
        [6.5, 3. , 5.2, 2. ],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [5.4, 3. , 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [6.5, 3. , 5.5, 1.8],
        [6.4, 2.8, 5.6, 2.2],
        [5. , 3. , 1.6, 0.2],
        [5.8, 2.8, 5.1, 2.4],
        [6.1, 2.6, 5.6, 1.4],
        [5.7, 2.5, 5. , 2. ],
        [7.1, 3. , 5.9, 2.1],
        [5.1, 3.4, 1.5, 0.2],
        [7.3, 2.9, 6.3, 1.8],
        [5.8, 2.6, 4. , 1.2],
        [5.5, 3.5, 1.3, 0.2],
        [5.2, 2.7, 3.9, 1.4],
        [4

In [26]:
X.shape, X_train.shape, X_test.shape, X_train.shape[0] / X.shape[0], X_test.shape[0] / X.shape[0]

((150, 4), (112, 4), (38, 4), 0.7466666666666667, 0.25333333333333335)

In [27]:
y.shape, y_train.shape, y_test.shape, y_train.shape[0] / y.shape[0], y_test.shape[0] / y.shape[0]

((150,), (112,), (38,), 0.7466666666666667, 0.25333333333333335)

In [30]:
y.reshape((150, 1)),y.reshape((-1,))

(array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [46]:
from sklearn.neighbors import KNeighborsClassifier

estimator = KNeighborsClassifier(n_neighbors=3)

estimator.fit(X_train, y_train)

y_predicted = estimator.predict(X_test)

print("Precisión: {:.1f}".format((y_test == y_predicted).mean() * 100))

Precisión: 100.0


In [47]:
X_test, y_test, y_predicted

(array([[4.4, 3.2, 1.3, 0.2],
        [6.1, 2.8, 4.7, 1.2],
        [6.7, 3.1, 5.6, 2.4],
        [5.8, 2.7, 3.9, 1.2],
        [4.9, 3.1, 1.5, 0.1],
        [6.4, 2.8, 5.6, 2.1],
        [6.2, 2.2, 4.5, 1.5],
        [7.7, 3. , 6.1, 2.3],
        [5. , 3.4, 1.6, 0.4],
        [6.3, 2.5, 5. , 1.9],
        [6.2, 2.9, 4.3, 1.3],
        [5.5, 2.4, 3.7, 1. ],
        [6. , 3. , 4.8, 1.8],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.6, 0.2],
        [6.3, 2.3, 4.4, 1.3],
        [4.3, 3. , 1.1, 0.1],
        [4.6, 3.2, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [5.9, 3.2, 4.8, 1.8],
        [5.5, 2.5, 4. , 1.3],
        [4.8, 3. , 1.4, 0.1],
        [5.9, 3. , 5.1, 1.8],
        [7.9, 3.8, 6.4, 2. ],
        [6.7, 3.1, 4.7, 1.5],
        [7.2, 3.6, 6.1, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [5.1, 3.3, 1.7, 0.5],
        [5.7, 3.8, 1.7, 0.3],
        [5. , 3.3, 1.4, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [5.5, 2.3, 4. , 1.3],
        [6.6, 2.9, 4.6, 1.3],
        [5

In [49]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(estimator, X, y, scoring='accuracy')

print(scores)

[0.96666667 0.96666667 0.93333333 0.96666667 1.        ]


In [51]:
accuracy = scores.mean() * 100

accuracy

96.66666666666669

In [58]:
import numpy as np

x = np.random.uniform(5, 20, (10, 4))

x

array([[11.96792558, 17.8625335 , 13.96191792, 15.46394262],
       [16.88005669, 19.80711835, 14.20203937, 12.6298682 ],
       [13.05110375, 13.13322881, 11.48382647, 16.27627167],
       [14.16116715,  6.07823082, 11.04984213, 12.14458106],
       [ 6.83527482, 18.1887144 , 13.65342308,  5.46502304],
       [13.57279444,  5.2299016 , 15.50625341, 14.76020602],
       [14.13279183, 13.7549775 , 13.39241367, 13.85777444],
       [17.50230794,  6.22224607, 15.69473963, 13.70838952],
       [16.1980375 ,  5.57616124, 10.99886376,  8.77045198],
       [17.04178596,  9.05951632,  7.49400735, 10.09564013]])

In [60]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler().fit_transform(x)

array([[0.48116948, 0.86660109, 0.78869915, 0.92486261],
       [0.94166595, 1.        , 0.81797964, 0.66272134],
       [0.58271394, 0.54216984, 0.48651986, 1.        ],
       [0.68677881, 0.05819556, 0.43359967, 0.6178341 ],
       [0.        , 0.88897716, 0.75108119, 0.        ],
       [0.63162076, 0.        , 0.97701593, 0.85976961],
       [0.68411872, 0.58482192, 0.71925361, 0.77629807],
       [1.        , 0.06807503, 1.        , 0.76248052],
       [0.87772885, 0.02375348, 0.42738335, 0.3057398 ],
       [0.95682755, 0.26271234, 0.        , 0.42831473]])

In [61]:
from sklearn.preprocessing import Normalizer

Normalizer().fit_transform(x)

array([[0.3997378 , 0.59662218, 0.46633866, 0.51650742],
       [0.52381385, 0.61464503, 0.4407109 , 0.39192403],
       [0.47989514, 0.48291492, 0.42226563, 0.59848606],
       [0.62887399, 0.26992417, 0.4907052 , 0.53932074],
       [0.28049421, 0.74639708, 0.56028562, 0.22426419],
       [0.52440968, 0.20206679, 0.5991124 , 0.5702875 ],
       [0.51253902, 0.49883723, 0.48568851, 0.50256526],
       [0.62696779, 0.22289334, 0.56221707, 0.49106202],
       [0.73073503, 0.25155494, 0.49618696, 0.39565759],
       [0.73984359, 0.39330532, 0.32534109, 0.43828708]])

In [66]:
from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(x)

array([[-7.17943583e-01,  1.16401985e+00,  5.13587566e-01,
         9.92861503e-01],
       [ 9.09934307e-01,  1.51929206e+00,  6.14822904e-01,
         9.86489722e-02],
       [-3.58978858e-01,  2.99984268e-01, -5.31177151e-01,
         1.24916910e+00],
       [ 8.89561837e-03, -9.88951360e-01, -7.14145185e-01,
        -5.44697475e-02],
       [-2.41890158e+00,  1.22361253e+00,  3.83525972e-01,
        -2.16201655e+00],
       [-1.86090814e-01, -1.14393960e+00,  1.16468026e+00,
         7.70817195e-01],
       [-5.07946989e-04,  4.13576652e-01,  2.73484264e-01,
         4.86080276e-01],
       [ 1.11614807e+00, -9.62640028e-01,  1.24414615e+00,
         4.38946062e-01],
       [ 6.83913474e-01, -1.08067858e+00, -7.35637696e-01,
        -1.11908135e+00],
       [ 9.63531308e-01, -4.44275783e-01, -2.21328708e+00,
        -7.00955471e-01]])

In [64]:
from sklearn.preprocessing import Binarizer

Binarizer().fit_transform(MinMaxScaler().fit_transform(x))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 0., 1.]])

In [102]:
X_broken = np.array(X)

X_broken[:,::3] /= 4

X_broken

array([[1.275, 3.5  , 1.4  , 0.05 ],
       [1.225, 3.   , 1.4  , 0.05 ],
       [1.175, 3.2  , 1.3  , 0.05 ],
       [1.15 , 3.1  , 1.5  , 0.05 ],
       [1.25 , 3.6  , 1.4  , 0.05 ],
       [1.35 , 3.9  , 1.7  , 0.1  ],
       [1.15 , 3.4  , 1.4  , 0.075],
       [1.25 , 3.4  , 1.5  , 0.05 ],
       [1.1  , 2.9  , 1.4  , 0.05 ],
       [1.225, 3.1  , 1.5  , 0.025],
       [1.35 , 3.7  , 1.5  , 0.05 ],
       [1.2  , 3.4  , 1.6  , 0.05 ],
       [1.2  , 3.   , 1.4  , 0.025],
       [1.075, 3.   , 1.1  , 0.025],
       [1.45 , 4.   , 1.2  , 0.05 ],
       [1.425, 4.4  , 1.5  , 0.1  ],
       [1.35 , 3.9  , 1.3  , 0.1  ],
       [1.275, 3.5  , 1.4  , 0.075],
       [1.425, 3.8  , 1.7  , 0.075],
       [1.275, 3.8  , 1.5  , 0.075],
       [1.35 , 3.4  , 1.7  , 0.05 ],
       [1.275, 3.7  , 1.5  , 0.1  ],
       [1.15 , 3.6  , 1.   , 0.05 ],
       [1.275, 3.3  , 1.7  , 0.125],
       [1.2  , 3.4  , 1.9  , 0.05 ],
       [1.25 , 3.   , 1.6  , 0.05 ],
       [1.25 , 3.4  , 1.6  , 0.1  ],
 

In [103]:
estimator = KNeighborsClassifier()

scores = cross_val_score(estimator, X_broken, y, scoring='accuracy')

scores.mean()

0.9466666666666667

In [104]:
from sklearn.pipeline import Pipeline

sequence = Pipeline([
    ('scale', MinMaxScaler()),
    ('estimate', KNeighborsClassifier())
])

scores = cross_val_score(sequence, X_broken, y, scoring='accuracy')

scores.mean()

0.96